/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BtButton {
        "action": 'primary' | 'secondary' | 'error';
        "emojis": boolean;
        "opensModal": boolean;
        "text": string;
    }
    interface BtInput {
        "name": string;
    }
    interface BtModal {
        "opened": boolean;
    }
}
declare global {
    interface HTMLBtButtonElement extends Components.BtButton, HTMLStencilElement {
    }
    var HTMLBtButtonElement: {
        prototype: HTMLBtButtonElement;
        new (): HTMLBtButtonElement;
    };
    interface HTMLBtInputElement extends Components.BtInput, HTMLStencilElement {
    }
    var HTMLBtInputElement: {
        prototype: HTMLBtInputElement;
        new (): HTMLBtInputElement;
    };
    interface HTMLBtModalElement extends Components.BtModal, HTMLStencilElement {
    }
    var HTMLBtModalElement: {
        prototype: HTMLBtModalElement;
        new (): HTMLBtModalElement;
    };
    interface HTMLElementTagNameMap {
        "bt-button": HTMLBtButtonElement;
        "bt-input": HTMLBtInputElement;
        "bt-modal": HTMLBtModalElement;
    }
}
declare namespace LocalJSX {
    interface BtButton {
        "action"?: 'primary' | 'secondary' | 'error';
        "emojis"?: boolean;
        "onOnButtonClickEvent"?: (event: CustomEvent<any>) => void;
        "opensModal"?: boolean;
        "text"?: string;
    }
    interface BtInput {
        "name"?: string;
    }
    interface BtModal {
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "bt-button": BtButton;
        "bt-input": BtInput;
        "bt-modal": BtModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bt-button": LocalJSX.BtButton & JSXBase.HTMLAttributes<HTMLBtButtonElement>;
            "bt-input": LocalJSX.BtInput & JSXBase.HTMLAttributes<HTMLBtInputElement>;
            "bt-modal": LocalJSX.BtModal & JSXBase.HTMLAttributes<HTMLBtModalElement>;
        }
    }
}
